# Generated by Django 4.1 on 2022-08-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=75)),
                ('descricao_curta', models.TextField(max_length=150, verbose_name='Descricao Curta')),
                ('descricao_longa', models.TextField(verbose_name='Descricao LOnga')),
                ('image', models.ImageField(blank=True, null=True, upload_to='produto_img/%Y,%m/')),
                ('slug', models.SlugField(unique=True)),
                ('preco_marketing', models.FloatField()),
                ('preco_marketing_promocional', models.FloatField(default=0)),
                ('tipo', models.CharField(choices=[('V', 'Variacao'), ('S', 'Simples')], default='V', max_length=1)),
            ],
        ),
    ]
